### ISSUE TITLE
docker-compose, persistent volume, Permission denied (os error 13)

### ISSUE THREAD

**Issue by FLevent29** [meilisearch/documentation#1331]
Hi!

I am on Windows 11 and I am trying to run MeiliSearch on Docker(4.3.0)(WSL 2 based engine) with a volume as persistent storage with the following `docker-compose.yaml`
```yaml
version: "3.1"
services:
  MeiliSearch:
    image: getmeili/meilisearch:v0.24.0
    ports:
      - "7700:7700"
    volumes:
      - "meili:/home/meili/data.ms"
    environment:
      MEILI_MASTER_KEY: "masterKey"
volumes:
  meili:
```
I am not sure what's going on, or if it is at all related to Windows, but I am getting ``Error: An internal error has occurred. `Permission denied (os error 13)`.`` and nothing else.
If I set `volumes` to some local path, like `"./.meili:/home/meili/data.ms"`, it works fine, although that's not ideal, and, if I understand correctly, slower.

Doing the same exact thing with `postgres:14.1` produces no errors, so it seems specific to MeiliSearch.
