### ISSUE TITLE
Typo in config file

### ISSUE THREAD

**Issue by dr497** [meilisearch/documentation#2131]
I believe that the `Run in production` guide contains a typo in the config file https://docs.meilisearch.com/learn/cookbooks/running_production.html#step-3-create-a-configuration-file `dump_dir` should be `dumps_dir` i.e the correct config file should be

```toml
env = "production"
master_key = "YOUR_MASTER_KEY_VALUE"
db_path = "/var/lib/meilisearch/data"
dumps_dir = "/var/lib/meilisearch/dumps"
snapshot_dir = "/var/lib/meilisearch/snapshots"
```
